[build-system]
requires = ["setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chebai-nl2fol"
version = "0.0.1"
description = "Translation of Natural language to First Order Logic for ChEBI."
authors = []
maintainers = []
readme = "README.md"
license = { text = "AGPL-3.0" }
requires-python = ">=3.14"
dependencies = [
    "chemlog >=1.0.7",
    "rdkit",
    "jsonargparse",
]

[project.optional-dependencies]
dev = [
    "langchain>=1.2.0",
    "PyYAML",
    "dotenv",
    "pytest>=7.0",
    "tqdm",
    "z3-solver>=4.15.3.0"
]

linter = [ "ruff",
    "isort",
    "pre-commit"]
anthropic = ["langchain-anthropic>=1.1.0"]
ollama = ["langchain-ollama>=1.0.1"]
groq = ["langchain-groq>=1.1.1"]


[tool.setuptools]
include-package-data = true
license-files = ["LICEN[CS]E*"]

[tool.setuptools.packages.find]
where = ["."]
include = ["nl_2_fol*"]

[tool.setuptools.package-data]
"nl_2_fol" = []

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
