[build-system]
requires = ["setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chebai-NL2FOL"
version = "0.0.0"
description = "Translation of Natural language to First Order Logic for ChEBI."
authors = []
maintainers = []
readme = "README.md"
license = { text = "AGPL-3.0" }
requires-python = ">=3.11, <3.14"
dependencies = [
    "langchain>=1.2.0",
    "PyYAML",
    "gavel @git+https://github.com/gavel-tool/python-gavel.git",
    "chemlog @git+https://github.com/sfluegel05/chemlog-peptides.git",
    "rdkit",
    "dotenv",
    "jsonargparse",
]

[project.optional-dependencies]
groq = ["langchain-groq>=1.1.1"]
anthropic = ["langchain-anthropic>=1.1.0"]

custom_host = [
    "torch",
    "transformers",
    "sentencepiece",
    "accelerate",
    "safetensors",
]

linters = ["ruff", "isort", "pre-commit"]
test = ["pytest>=7.0"]


[tool.setuptools]
include-package-data = true
license-files = ["LICEN[CS]E*"]

[tool.setuptools.packages.find]
where = ["."]
include = ["nl_2_fol*"]

[tool.setuptools.package-data]
"nl_2_fol" = []

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
